### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by wesm** [conda-forge/feather-format-feedstock#1]
With https://github.com/wesm/feather/pull/146, we should be able to create Windows builds. It might be nice to verify the builds before making a PyPI release

**Comment by chris-b1** [comment]
Here's the set of steps I used to build - it should basically just work with python 3.5

```
conda create -n feather35 python=3.5 pandas numpy cython
activate feather35
git clone https://github.com/wesm/feather.git
cd feather\
robocopy cpp\src\ python\src /E
cd python\
python setup.py install
```

For python 2.7, a couple extra steps so that MSVC 2015 is used.

```
[...]
"%VS140COMNTOOLS%\..\..\VC\vcvarsall.bat" x64
set DISTUTILS_USE_SDK=1
set MSSdk=1
python setup.py install
```

(stolen from https://github.com/pybind/pbtest)

**Comment by msarahan** [comment]
If c++11 is necessary, the best way is to add

```
build:
    msvc_compiler: 14.0
```

To meta.yaml.  this does exactly what you posted, but is tied into conda-build.

You should also then pin the appropriate msvc runtime as a run requirement:

```
requirements:
    run:
        - vs2015_runtime
```

Finally, be very careful with this. You are mixing msvc runtimes, and this can lead to subtle bugs and out right crashes.  Unfortunately, there's not really a good way to have both c++11 and python 2.7.  There is some work towards making it easier to have a complete python 2.7 ecosystem with a newer compiler, but that's not really ready for conda forge yet.

**Comment by jjhelmus** [comment]
Created PR #2 which is running builds on the current master branch of the Git repo including on Windows.

**Comment by jjhelmus** [comment]
Summary from the PR.  Current master branch builds and imports on Windows using Visual Studio 2015 but not with previous versions of Visual Studio.
